### ISSUE TITLE
Problem with the code.

### ISSUE THREAD

**Issue by FrankArn7** [ErenKrt/Fivem-Server-Status#3]
The code is great used it as a back burner for my own Fivem Launcher, However there is one problem. When the server is offline, it will open the program fine but the player count goes back to being "label1" and when the player updater counts down from 20 and hits 1 the program crashes. This being the error message from VS: "label1.Text = Server.GetOnlinePlayersCount().ToString() + " / " + Server.GetMaxPlayersCount();" "System.NullReferenceException: 'Object reference not set to an instance of an object.'" 

btw the server offline status works perfect its just the player count that doesn't. (Shows up offline in red) When offline. 

Few Questions: 
Can you help me fix this problem maybe make it to when it hits 1 and crashes because the server is offline update the text to "Offline" for the player count? Instead of encountering this crash? 

screenshot of when the program stops working: http://prntscr.com/s4fopz

This is my only problem with the code everything else works perfectly.

**Comment by FrankArn7** [comment]
Figured out a really shitty way to make it from stop crashing but what I really want maybe you can help me with it is a way for the program to continuously check if the server is ONLINE or OFFLINE every 20 secs, this way I can make it so when the server is pinging the program it shows ONLINE and updates the number of players on it. When the server is OFFLINE I want it to show "Server is Offline" in those texts, then if the server comes back online for the program to recognize it and swap back to the text "Server is Online" with the player count updating every 20 secs. 

Is this possible? 
How can I do it? 
Any help would be awesome man!

**Comment by StefanoMigotto** [comment]
did you manage to solve?

**Comment by ErenKrt** [comment]
Sorry to see this so late, i wish you had emailed. I'm updating the code and preparing a sample code for you.

**Comment by StefanoMigotto** [comment]
Thanks, but some time ago I had already fixed it by changing by modifying the code, if I remembered what the error was I would have passed it to you but unfortunately I don't have it anymore, sorry

**Comment by ErenKrt** [comment]
New [version ](https://github.com/ErenKrt/Fivem-Server-Status/releases/tag/V3) published.
[Example added](https://github.com/ErenKrt/Fivem-Server-Status/blob/master/README.md#timer-example)
